"""change type to field mane

Revision ID: ebc0542ed390
Revises: ae91c6e3b2e6
Create Date: 2023-10-04 22:35:32.250287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc0542ed390'
down_revision = 'ae91c6e3b2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.CHAR(length=8),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
